[[transaction]]
date = "2020-01-01"
description = "income"
account = "Equity:opening balance"
[[transaction.post]]
amount = 3000
account = "Assets:checking"
[[transaction.post]]
amount = 10000
account = "Assets:savings"

[[transaction]]
date = "2020-01-01"
description = "Sample really long that would cause wrap"
account = "Assets:checking"
# amount and account_offset are optional
    # indention is optional
    [[transaction.post]]
    amount = 10.00
    account = "Expenses:general"
    [[transaction.post]]
    amount = 10.00
    account = "Expenses:general"
    [[transaction.post]]
    amount = -10.00
    account = "Assets:savings"

# demonstrates that transaction posts can be split up in a file
[default]
account = "Assets:checking"
account_offset = "Expenses:general"

[[transaction]]
date = "2020-01-01"
description = "Sample transaction"
account = "Assets:checking"
amount = 20.00
account_offset = "Expenses:general"
# if posts are supplied amount and account_offset above are ignored
[[transaction.post]]
amount = 10.00
account = "Expenses:general"
[[transaction.post]]
amount = 10.00
account = "Expenses:general"

[[transaction]]
date = "2020-01-01"
description = "Movie night"
account = "Liabilities:credit"
amount = 15.00
account_offset = "Expenses:entertainment"


# Virtual transaction as funds (funds of virtual cash)
[[transaction]]
date = "2020-08-01"
description = "funding bank funds"
[[transaction.fund]]
account = "Fund:Auto"
amount = 1000

[[transaction]]
date = "2020-08-01"
description = "Car Repair"
account = "Assets:savings"
account_offset = "Expenses:general"
amount = 20
[[transaction.fund]]
account = "Fund:Auto"
amount = -20

