image: "rust:latest"

before_script:
- rustup component add rustfmt

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
    - cargo fmt -- --check
