[[transaction]]
date = "2020-01-01"
description = "income"
account = "Equity:opening balance"
[[transaction.entry]]
amount = 3000
account = "Assets:checking"
[[transaction.entry]]
amount = 10000
account = "Assets:savings"

[[transaction]]
date = "2020-01-01"
description = "Sample transaction"
account = "Assets:checking"
# amount and account_offset are optional
    [[transaction.entry]]
    amount = 10.00
    account = "Expenses:general"
    [[transaction.entry]]
    amount = 10.00
    account = "Expenses:general"
    [[transaction.entry]]
    amount = -10.00
    account = "Assets:savings"

# demonstrates that transaction entries can be split up in a file
[default]
account = "Assets:checking"
account_offset = "Expenses:general"

[[transaction]]
date = "2020-01-01"
description = "Sample transaction"
account = "Assets:checking"
amount = 20.00
account_offset = "Expenses:general"
# if entries are supplied amount and account_offset above are ignored
[[transaction.entry]]
amount = 10.00
account = "Expenses:general"
[[transaction.entry]]
amount = 10.00
account = "Expenses:general"

[[transaction]]
date = "2020-01-01"
description = "Movie night"
account = "Liabilities:credit"
amount = 15.00
account_offset = "Expenses:entertainment"